version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres
    deploy:
      restart_policy:
        condition: none
        max_attempts: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${WEBAPI_DB_NAME}


  api:
    image: pantyporowicz/osp-webapp-api:latest
    deploy:
      restart_policy:
        condition: none
        max_attempts: 5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${WEBAPI_DB_NAME}
    command:
      npm run start
