version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres
    deploy:
      restart_policy:
        condition: none
        max_attempts: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${WEBAPI_DB_NAME}

  api:
    image: pantyporowicz/osp-webapp-api:latest
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${WEBAPI_DB_NAME}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      FACEBOOK_REDIRECT_URL: ${FACEBOOK_REDIRECT_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      FRONTEND_LOGIN_PAGES_SUCCESS: ${FRONTEND_LOGIN_PAGES_SUCCESS}
      FRONTEND_LOGIN_PAGES_FAILED: ${FRONTEND_LOGIN_PAGES_FAILED}
      SENTRY_DSN: ${SENTRY_DSN}
    command:
      npm run start

  nginx:
    image: nginx
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
