version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres
    deploy:
      restart_policy:
        condition: none
        max_attempts: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  front:
    image: pantyporowicz/osp-webapp-frontend:latest
    command:
      yarn start

  nginx:
    image: nginx
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  rabbit:
    image: rabbitmq:3.9-management
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT__USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT__PASSWORD}
