name: Deploy staging

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy staging
    runs-on: ubuntu-latest
    env:
      ENV: staging
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
      SERVER_USER_NAME: ${{ secrets.SERVER_USERNAME }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Deploy staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: cd osp/infra && git pull && ENV=${{ env.ENV }} make deploy
